language: node_js
node_js:
- stable
addons:
  ssh_known_hosts:
  - mint.isi.edu
  - 54.148.90.74
env:
  - NODE_ENV=production
install: yarn
cache: yarn
script: yarn build
before_deploy:
- echo $key_pass | gpg --passphrase-fd 0 id_travis_rsa.gpg
- eval "$(ssh-agent -s)"
- chmod 600 id_travis_rsa
- ssh-add id_travis_rsa
- mv build mint-ui-lit
deploy:
- provider: script
  skip_cleanup: true
  script: bash scripts/deploy.sh $TRAVIS_BUILD_DIR/mint-ui-lit mintui_$TRAVIS_BRANCH
  on:
    all_branches: true
    condition: "$TRAVIS_BRANCH =~ ^(master|dev|enviroments)$"
- provider: script
  skip_cleanup: true
  script: bash scripts/deploy.sh $TRAVIS_BUILD_DIR/mint-ui-lit mintui_$TRAVIS_TAG
  on:
    tags: true
    all_branches: true
